# Generated by Django 5.2.4 on 2026-09-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0038_add_purchase_process"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierTotvs",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_column="CODCFO",
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(db_column="NOMEFANTASIA", max_length=100),
                ),
                ("legal_name", models.CharField(db_column="NOME", max_length=100)),
                ("cnpj", models.CharField(db_column="CGCCFO", max_length=20)),
                (
                    "email",
                    models.EmailField(blank=True, db_column="EMAIL", max_length=254),
                ),
                (
                    "phone",
                    models.CharField(blank=True, db_column="TELEFONE", max_length=20),
                ),
                (
                    "city",
                    models.CharField(blank=True, db_column="CIDADE", max_length=32),
                ),
                (
                    "state",
                    models.CharField(blank=True, db_column="CODETD", max_length=2),
                ),
                (
                    "street",
                    models.CharField(blank=True, db_column="RUA", max_length=100),
                ),
                (
                    "number",
                    models.CharField(blank=True, db_column="NUMERO", max_length=8),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True, db_column="COMPLEMENTO", max_length=60
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(blank=True, db_column="BAIRRO", max_length=80),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, db_column="CEP", max_length=9),
                ),
                (
                    "type_supplier",
                    models.CharField(blank=True, db_column="CODTCF", max_length=25),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_column="PESSOAFISOUJUR", max_length=1
                    ),
                ),
                (
                    "municipal_registration",
                    models.CharField(
                        blank=True, db_column="INSCRMUNICIPAL", max_length=20
                    ),
                ),
                (
                    "state_registration",
                    models.CharField(
                        blank=True, db_column="INSCRESTADUAL", max_length=20
                    ),
                ),
                ("active", models.SmallIntegerField(db_column="ATIVO")),
            ],
            options={
                "verbose_name": "Fornecedor TOTVS",
                "verbose_name_plural": "Fornecedores TOTVS",
                "db_table": "FCFO",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierTypeTotvs",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_column="CODTCF",
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="DESCRICAO", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Tipo de Fornecedor TOTVS",
                "verbose_name_plural": "Tipos de Fornecedores TOTVS",
                "db_table": "FTCF",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="purchaseprocess",
            name="compliance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Conformidade & Evidências Obrigatórias",
            ),
        ),
    ]
