"""add has assurance to maintenance

Revision ID: 01b0eafaaf2d
Revises: 1a262007e6fa
Create Date: 2024-04-19 16:00:38.943598

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01b0eafaaf2d"
down_revision: str | None = "1a262007e6fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "maintenance", sa.Column("has_assurance", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maintenance", "has_assurance")
    # ### end Alembic commands ###
