"""add has asset to employee

Revision ID: cabf15fffa87
Revises: fdd4419118a9
Create Date: 2025-11-12 00:00:59.963907

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cabf15fffa87"
down_revision: str | None = "fdd4419118a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("has_solutis_asset", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "employees", sa.Column("has_personal_asset", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "employees", sa.Column("has_other_asset", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "has_other_asset")
    op.drop_column("employees", "has_personal_asset")
    op.drop_column("employees", "has_solutis_asset")
    op.create_index(
        "ix_apscheduler_jobs_next_run_time",
        "apscheduler_jobs",
        ["next_run_time"],
        unique=False,
    )
    # ### end Alembic commands ###
