/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as InventoryRouteRouteImport } from './routes/_inventory/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersApprovalRouteRouteImport } from './routes/_suppliers/approval/route'
import { Route as InventoryInventoryFormRouteRouteImport } from './routes/_inventory/inventory-form/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as SuppliersApprovalIndexRouteImport } from './routes/_suppliers/approval/index'
import { Route as InventoryInventoryFormIndexRouteImport } from './routes/_inventory/inventory-form/index'
import { Route as InventoryInventoryAccessIndexRouteImport } from './routes/_inventory/inventory-access/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardTermsIndexRouteImport } from './routes/_dashboard/terms/index'
import { Route as DashboardSuppliersIndexRouteImport } from './routes/_dashboard/suppliers/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/_dashboard/reports/index'
import { Route as DashboardLendingsIndexRouteImport } from './routes/_dashboard/lendings/index'
import { Route as DashboardInvoicesIndexRouteImport } from './routes/_dashboard/invoices/index'
import { Route as DashboardInventoryIndexRouteImport } from './routes/_dashboard/inventory/index'
import { Route as DashboardGroupsAndPermissionsIndexRouteImport } from './routes/_dashboard/groups-and-permissions/index'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/_dashboard/employees/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardAssetsIndexRouteImport } from './routes/_dashboard/assets/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as DashboardUsersAddIndexRouteImport } from './routes/_dashboard/users/add/index'
import { Route as DashboardTermsAddIndexRouteImport } from './routes/_dashboard/terms/add/index'
import { Route as DashboardSuppliersAddIndexRouteImport } from './routes/_dashboard/suppliers/add/index'
import { Route as DashboardLendingsAddIndexRouteImport } from './routes/_dashboard/lendings/add/index'
import { Route as DashboardInvoicesImportIndexRouteImport } from './routes/_dashboard/invoices/import/index'
import { Route as DashboardInventoryViewIndexRouteImport } from './routes/_dashboard/inventory/view/index'
import { Route as DashboardGroupsAndPermissionsAddIndexRouteImport } from './routes/_dashboard/groups-and-permissions/add/index'
import { Route as DashboardEmployeesAddIndexRouteImport } from './routes/_dashboard/employees/add/index'
import { Route as DashboardAssetsImportIndexRouteImport } from './routes/_dashboard/assets/import/index'
import { Route as DashboardAssetsAddIndexRouteImport } from './routes/_dashboard/assets/add/index'
import { Route as DashboardUsersEditIdRouteImport } from './routes/_dashboard/users/edit/$id'
import { Route as DashboardTermsEditIdRouteImport } from './routes/_dashboard/terms/edit/$id'
import { Route as DashboardLendingsEditIdRouteImport } from './routes/_dashboard/lendings/edit/$id'
import { Route as DashboardGroupsAndPermissionsEditIdRouteImport } from './routes/_dashboard/groups-and-permissions/edit/$id'
import { Route as DashboardEmployeesEditIdRouteImport } from './routes/_dashboard/employees/edit/$id'
import { Route as DashboardAssetsEditIdRouteImport } from './routes/_dashboard/assets/edit/$id'
import { Route as DashboardSuppliersEditIdIndexRouteImport } from './routes/_dashboard/suppliers/edit/$id/index'
import { Route as DashboardAssetEvaluationsIndexRouteImport } from './routes/_dashboard/asset-evaluations/index'
import { Route as DashboardAssetEvaluationsNewIndexRouteImport } from './routes/_dashboard/asset-evaluations/new/index'
import { Route as DashboardAssetEvaluationsIdRouteImport } from './routes/_dashboard/asset-evaluations/$id'
import { Route as DashboardPurchaseProcessesIndexRouteImport } from './routes/_dashboard/purchase-processes/index'
import { Route as DashboardPurchaseProcessesNewIndexRouteImport } from './routes/_dashboard/purchase-processes/new/index'
import { Route as DashboardPurchaseProcessesIdRouteImport } from './routes/_dashboard/purchase-processes/$id'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRouteRoute = InventoryRouteRouteImport.update({
  id: '/_inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersApprovalRouteRoute = SuppliersApprovalRouteRouteImport.update({
  id: '/_suppliers/approval',
  path: '/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInventoryFormRouteRoute =
  InventoryInventoryFormRouteRouteImport.update({
    id: '/inventory-form',
    path: '/inventory-form',
    getParentRoute: () => InventoryRouteRoute,
  } as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersApprovalIndexRoute = SuppliersApprovalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuppliersApprovalRouteRoute,
} as any)
const InventoryInventoryFormIndexRoute =
  InventoryInventoryFormIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InventoryInventoryFormRouteRoute,
  } as any)
const InventoryInventoryAccessIndexRoute =
  InventoryInventoryAccessIndexRouteImport.update({
    id: '/inventory-access/',
    path: '/inventory-access/',
    getParentRoute: () => InventoryRouteRoute,
  } as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTermsIndexRoute = DashboardTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSuppliersIndexRoute = DashboardSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLendingsIndexRoute = DashboardLendingsIndexRouteImport.update({
  id: '/lendings/',
  path: '/lendings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesIndexRoute = DashboardInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGroupsAndPermissionsIndexRoute =
  DashboardGroupsAndPermissionsIndexRouteImport.update({
    id: '/groups-and-permissions/',
    path: '/groups-and-permissions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAssetsIndexRoute = DashboardAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLoginRouteRoute,
} as any)
const DashboardUsersAddIndexRoute = DashboardUsersAddIndexRouteImport.update({
  id: '/users/add/',
  path: '/users/add/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTermsAddIndexRoute = DashboardTermsAddIndexRouteImport.update({
  id: '/terms/add/',
  path: '/terms/add/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSuppliersAddIndexRoute =
  DashboardSuppliersAddIndexRouteImport.update({
    id: '/suppliers/add/',
    path: '/suppliers/add/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLendingsAddIndexRoute =
  DashboardLendingsAddIndexRouteImport.update({
    id: '/lendings/add/',
    path: '/lendings/add/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInvoicesImportIndexRoute =
  DashboardInvoicesImportIndexRouteImport.update({
    id: '/invoices/import/',
    path: '/invoices/import/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInventoryViewIndexRoute =
  DashboardInventoryViewIndexRouteImport.update({
    id: '/inventory/view/',
    path: '/inventory/view/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardGroupsAndPermissionsAddIndexRoute =
  DashboardGroupsAndPermissionsAddIndexRouteImport.update({
    id: '/groups-and-permissions/add/',
    path: '/groups-and-permissions/add/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmployeesAddIndexRoute =
  DashboardEmployeesAddIndexRouteImport.update({
    id: '/employees/add/',
    path: '/employees/add/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAssetsImportIndexRoute =
  DashboardAssetsImportIndexRouteImport.update({
    id: '/assets/import/',
    path: '/assets/import/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAssetsAddIndexRoute = DashboardAssetsAddIndexRouteImport.update({
  id: '/assets/add/',
  path: '/assets/add/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersEditIdRoute = DashboardUsersEditIdRouteImport.update({
  id: '/users/edit/$id',
  path: '/users/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTermsEditIdRoute = DashboardTermsEditIdRouteImport.update({
  id: '/terms/edit/$id',
  path: '/terms/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLendingsEditIdRoute = DashboardLendingsEditIdRouteImport.update({
  id: '/lendings/edit/$id',
  path: '/lendings/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGroupsAndPermissionsEditIdRoute =
  DashboardGroupsAndPermissionsEditIdRouteImport.update({
    id: '/groups-and-permissions/edit/$id',
    path: '/groups-and-permissions/edit/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmployeesEditIdRoute =
  DashboardEmployeesEditIdRouteImport.update({
    id: '/employees/edit/$id',
    path: '/employees/edit/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAssetsEditIdRoute = DashboardAssetsEditIdRouteImport.update({
  id: '/assets/edit/$id',
  path: '/assets/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSuppliersEditIdIndexRoute =
  DashboardSuppliersEditIdIndexRouteImport.update({
    id: '/suppliers/edit/$id/',
    path: '/suppliers/edit/$id/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAssetEvaluationsIndexRoute =
  DashboardAssetEvaluationsIndexRouteImport.update({
    id: '/asset-evaluations/',
    path: '/asset-evaluations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAssetEvaluationsNewIndexRoute =
  DashboardAssetEvaluationsNewIndexRouteImport.update({
    id: '/asset-evaluations/new/',
    path: '/asset-evaluations/new/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAssetEvaluationsIdRoute =
  DashboardAssetEvaluationsIdRouteImport.update({
    id: '/asset-evaluations/$id',
    path: '/asset-evaluations/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPurchaseProcessesIndexRoute =
  DashboardPurchaseProcessesIndexRouteImport.update({
    id: '/purchase-processes/',
    path: '/purchase-processes/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPurchaseProcessesNewIndexRoute =
  DashboardPurchaseProcessesNewIndexRouteImport.update({
    id: '/purchase-processes/new/',
    path: '/purchase-processes/new/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPurchaseProcessesIdRoute =
  DashboardPurchaseProcessesIdRouteImport.update({
    id: '/purchase-processes/$id',
    path: '/purchase-processes/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof AuthLoginRouteRouteWithChildren
  '/inventory-form': typeof InventoryInventoryFormRouteRouteWithChildren
  '/approval': typeof SuppliersApprovalRouteRouteWithChildren
  '/login/': typeof AuthLoginIndexRoute
  '/assets': typeof DashboardAssetsIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/employees': typeof DashboardEmployeesIndexRoute
  '/groups-and-permissions': typeof DashboardGroupsAndPermissionsIndexRoute
  '/inventory': typeof DashboardInventoryIndexRoute
  '/invoices': typeof DashboardInvoicesIndexRoute
  '/lendings': typeof DashboardLendingsIndexRoute
  '/reports': typeof DashboardReportsIndexRoute
  '/suppliers': typeof DashboardSuppliersIndexRoute
  '/terms': typeof DashboardTermsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/inventory-access': typeof InventoryInventoryAccessIndexRoute
  '/inventory-form/': typeof InventoryInventoryFormIndexRoute
  '/approval/': typeof SuppliersApprovalIndexRoute
  '/assets/edit/$id': typeof DashboardAssetsEditIdRoute
  '/employees/edit/$id': typeof DashboardEmployeesEditIdRoute
  '/groups-and-permissions/edit/$id': typeof DashboardGroupsAndPermissionsEditIdRoute
  '/lendings/edit/$id': typeof DashboardLendingsEditIdRoute
  '/terms/edit/$id': typeof DashboardTermsEditIdRoute
  '/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/assets/add': typeof DashboardAssetsAddIndexRoute
  '/assets/import': typeof DashboardAssetsImportIndexRoute
  '/employees/add': typeof DashboardEmployeesAddIndexRoute
  '/groups-and-permissions/add': typeof DashboardGroupsAndPermissionsAddIndexRoute
  '/inventory/view': typeof DashboardInventoryViewIndexRoute
  '/invoices/import': typeof DashboardInvoicesImportIndexRoute
  '/lendings/add': typeof DashboardLendingsAddIndexRoute
  '/suppliers/add': typeof DashboardSuppliersAddIndexRoute
  '/terms/add': typeof DashboardTermsAddIndexRoute
  '/users/add': typeof DashboardUsersAddIndexRoute
  '/suppliers/edit/$id': typeof DashboardSuppliersEditIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof AuthLoginIndexRoute
  '/assets': typeof DashboardAssetsIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/employees': typeof DashboardEmployeesIndexRoute
  '/groups-and-permissions': typeof DashboardGroupsAndPermissionsIndexRoute
  '/inventory': typeof DashboardInventoryIndexRoute
  '/invoices': typeof DashboardInvoicesIndexRoute
  '/lendings': typeof DashboardLendingsIndexRoute
  '/reports': typeof DashboardReportsIndexRoute
  '/suppliers': typeof DashboardSuppliersIndexRoute
  '/terms': typeof DashboardTermsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/inventory-access': typeof InventoryInventoryAccessIndexRoute
  '/inventory-form': typeof InventoryInventoryFormIndexRoute
  '/approval': typeof SuppliersApprovalIndexRoute
  '/assets/edit/$id': typeof DashboardAssetsEditIdRoute
  '/employees/edit/$id': typeof DashboardEmployeesEditIdRoute
  '/groups-and-permissions/edit/$id': typeof DashboardGroupsAndPermissionsEditIdRoute
  '/lendings/edit/$id': typeof DashboardLendingsEditIdRoute
  '/terms/edit/$id': typeof DashboardTermsEditIdRoute
  '/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/assets/add': typeof DashboardAssetsAddIndexRoute
  '/assets/import': typeof DashboardAssetsImportIndexRoute
  '/employees/add': typeof DashboardEmployeesAddIndexRoute
  '/groups-and-permissions/add': typeof DashboardGroupsAndPermissionsAddIndexRoute
  '/inventory/view': typeof DashboardInventoryViewIndexRoute
  '/invoices/import': typeof DashboardInvoicesImportIndexRoute
  '/lendings/add': typeof DashboardLendingsAddIndexRoute
  '/suppliers/add': typeof DashboardSuppliersAddIndexRoute
  '/terms/add': typeof DashboardTermsAddIndexRoute
  '/users/add': typeof DashboardUsersAddIndexRoute
  '/suppliers/edit/$id': typeof DashboardSuppliersEditIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_inventory': typeof InventoryRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/_auth/login': typeof AuthLoginRouteRouteWithChildren
  '/_inventory/inventory-form': typeof InventoryInventoryFormRouteRouteWithChildren
  '/_suppliers/approval': typeof SuppliersApprovalRouteRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_dashboard/assets/': typeof DashboardAssetsIndexRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/_dashboard/groups-and-permissions/': typeof DashboardGroupsAndPermissionsIndexRoute
  '/_dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/_dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/_dashboard/lendings/': typeof DashboardLendingsIndexRoute
  '/_dashboard/reports/': typeof DashboardReportsIndexRoute
  '/_dashboard/suppliers/': typeof DashboardSuppliersIndexRoute
  '/_dashboard/terms/': typeof DashboardTermsIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_inventory/inventory-access/': typeof InventoryInventoryAccessIndexRoute
  '/_inventory/inventory-form/': typeof InventoryInventoryFormIndexRoute
  '/_suppliers/approval/': typeof SuppliersApprovalIndexRoute
  '/_dashboard/assets/edit/$id': typeof DashboardAssetsEditIdRoute
  '/_dashboard/employees/edit/$id': typeof DashboardEmployeesEditIdRoute
  '/_dashboard/groups-and-permissions/edit/$id': typeof DashboardGroupsAndPermissionsEditIdRoute
  '/_dashboard/lendings/edit/$id': typeof DashboardLendingsEditIdRoute
  '/_dashboard/terms/edit/$id': typeof DashboardTermsEditIdRoute
  '/_dashboard/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/_dashboard/assets/add/': typeof DashboardAssetsAddIndexRoute
  '/_dashboard/assets/import/': typeof DashboardAssetsImportIndexRoute
  '/_dashboard/employees/add/': typeof DashboardEmployeesAddIndexRoute
  '/_dashboard/groups-and-permissions/add/': typeof DashboardGroupsAndPermissionsAddIndexRoute
  '/_dashboard/inventory/view/': typeof DashboardInventoryViewIndexRoute
  '/_dashboard/invoices/import/': typeof DashboardInvoicesImportIndexRoute
  '/_dashboard/lendings/add/': typeof DashboardLendingsAddIndexRoute
  '/_dashboard/suppliers/add/': typeof DashboardSuppliersAddIndexRoute
  '/_dashboard/terms/add/': typeof DashboardTermsAddIndexRoute
  '/_dashboard/users/add/': typeof DashboardUsersAddIndexRoute
  '/_dashboard/suppliers/edit/$id/': typeof DashboardSuppliersEditIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/login'
    | '/inventory-form'
    | '/approval'
    | '/login/'
    | '/assets'
    | '/dashboard'
    | '/employees'
    | '/groups-and-permissions'
    | '/inventory'
    | '/invoices'
    | '/lendings'
    | '/reports'
    | '/suppliers'
    | '/terms'
    | '/users'
    | '/inventory-access'
    | '/inventory-form/'
    | '/approval/'
    | '/assets/edit/$id'
    | '/employees/edit/$id'
    | '/groups-and-permissions/edit/$id'
    | '/lendings/edit/$id'
    | '/terms/edit/$id'
    | '/users/edit/$id'
    | '/assets/add'
    | '/assets/import'
    | '/employees/add'
    | '/groups-and-permissions/add'
    | '/inventory/view'
    | '/invoices/import'
    | '/lendings/add'
    | '/suppliers/add'
    | '/terms/add'
    | '/users/add'
    | '/suppliers/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/login'
    | '/assets'
    | '/dashboard'
    | '/employees'
    | '/groups-and-permissions'
    | '/inventory'
    | '/invoices'
    | '/lendings'
    | '/reports'
    | '/suppliers'
    | '/terms'
    | '/users'
    | '/inventory-access'
    | '/inventory-form'
    | '/approval'
    | '/assets/edit/$id'
    | '/employees/edit/$id'
    | '/groups-and-permissions/edit/$id'
    | '/lendings/edit/$id'
    | '/terms/edit/$id'
    | '/users/edit/$id'
    | '/assets/add'
    | '/assets/import'
    | '/employees/add'
    | '/groups-and-permissions/add'
    | '/inventory/view'
    | '/invoices/import'
    | '/lendings/add'
    | '/suppliers/add'
    | '/terms/add'
    | '/users/add'
    | '/suppliers/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_inventory'
    | '/error'
    | '/_auth/login'
    | '/_inventory/inventory-form'
    | '/_suppliers/approval'
    | '/_auth/login/'
    | '/_dashboard/assets/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/employees/'
    | '/_dashboard/groups-and-permissions/'
    | '/_dashboard/inventory/'
    | '/_dashboard/invoices/'
    | '/_dashboard/lendings/'
    | '/_dashboard/reports/'
    | '/_dashboard/suppliers/'
    | '/_dashboard/terms/'
    | '/_dashboard/users/'
    | '/_inventory/inventory-access/'
    | '/_inventory/inventory-form/'
    | '/_suppliers/approval/'
    | '/_dashboard/assets/edit/$id'
    | '/_dashboard/employees/edit/$id'
    | '/_dashboard/groups-and-permissions/edit/$id'
    | '/_dashboard/lendings/edit/$id'
    | '/_dashboard/terms/edit/$id'
    | '/_dashboard/users/edit/$id'
    | '/_dashboard/assets/add/'
    | '/_dashboard/assets/import/'
    | '/_dashboard/employees/add/'
    | '/_dashboard/groups-and-permissions/add/'
    | '/_dashboard/inventory/view/'
    | '/_dashboard/invoices/import/'
    | '/_dashboard/lendings/add/'
    | '/_dashboard/suppliers/add/'
    | '/_dashboard/terms/add/'
    | '/_dashboard/users/add/'
    | '/_dashboard/suppliers/edit/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  InventoryRouteRoute: typeof InventoryRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRouteWithChildren
  SuppliersApprovalRouteRoute: typeof SuppliersApprovalRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_inventory': {
      id: '/_inventory'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof InventoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_suppliers/approval': {
      id: '/_suppliers/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof SuppliersApprovalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_inventory/inventory-form': {
      id: '/_inventory/inventory-form'
      path: '/inventory-form'
      fullPath: '/inventory-form'
      preLoaderRoute: typeof InventoryInventoryFormRouteRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_suppliers/approval/': {
      id: '/_suppliers/approval/'
      path: '/'
      fullPath: '/approval/'
      preLoaderRoute: typeof SuppliersApprovalIndexRouteImport
      parentRoute: typeof SuppliersApprovalRouteRoute
    }
    '/_inventory/inventory-form/': {
      id: '/_inventory/inventory-form/'
      path: '/'
      fullPath: '/inventory-form/'
      preLoaderRoute: typeof InventoryInventoryFormIndexRouteImport
      parentRoute: typeof InventoryInventoryFormRouteRoute
    }
    '/_inventory/inventory-access/': {
      id: '/_inventory/inventory-access/'
      path: '/inventory-access'
      fullPath: '/inventory-access'
      preLoaderRoute: typeof InventoryInventoryAccessIndexRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/terms/': {
      id: '/_dashboard/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof DashboardTermsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/suppliers/': {
      id: '/_dashboard/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof DashboardSuppliersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/reports/': {
      id: '/_dashboard/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/lendings/': {
      id: '/_dashboard/lendings/'
      path: '/lendings'
      fullPath: '/lendings'
      preLoaderRoute: typeof DashboardLendingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/invoices/': {
      id: '/_dashboard/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof DashboardInvoicesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/inventory/': {
      id: '/_dashboard/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/groups-and-permissions/': {
      id: '/_dashboard/groups-and-permissions/'
      path: '/groups-and-permissions'
      fullPath: '/groups-and-permissions'
      preLoaderRoute: typeof DashboardGroupsAndPermissionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/employees/': {
      id: '/_dashboard/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/assets/': {
      id: '/_dashboard/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof DashboardAssetsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthLoginRouteRoute
    }
    '/_dashboard/users/add/': {
      id: '/_dashboard/users/add/'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof DashboardUsersAddIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/terms/add/': {
      id: '/_dashboard/terms/add/'
      path: '/terms/add'
      fullPath: '/terms/add'
      preLoaderRoute: typeof DashboardTermsAddIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/suppliers/add/': {
      id: '/_dashboard/suppliers/add/'
      path: '/suppliers/add'
      fullPath: '/suppliers/add'
      preLoaderRoute: typeof DashboardSuppliersAddIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/lendings/add/': {
      id: '/_dashboard/lendings/add/'
      path: '/lendings/add'
      fullPath: '/lendings/add'
      preLoaderRoute: typeof DashboardLendingsAddIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/invoices/import/': {
      id: '/_dashboard/invoices/import/'
      path: '/invoices/import'
      fullPath: '/invoices/import'
      preLoaderRoute: typeof DashboardInvoicesImportIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/inventory/view/': {
      id: '/_dashboard/inventory/view/'
      path: '/inventory/view'
      fullPath: '/inventory/view'
      preLoaderRoute: typeof DashboardInventoryViewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/groups-and-permissions/add/': {
      id: '/_dashboard/groups-and-permissions/add/'
      path: '/groups-and-permissions/add'
      fullPath: '/groups-and-permissions/add'
      preLoaderRoute: typeof DashboardGroupsAndPermissionsAddIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/employees/add/': {
      id: '/_dashboard/employees/add/'
      path: '/employees/add'
      fullPath: '/employees/add'
      preLoaderRoute: typeof DashboardEmployeesAddIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/assets/import/': {
      id: '/_dashboard/assets/import/'
      path: '/assets/import'
      fullPath: '/assets/import'
      preLoaderRoute: typeof DashboardAssetsImportIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/assets/add/': {
      id: '/_dashboard/assets/add/'
      path: '/assets/add'
      fullPath: '/assets/add'
      preLoaderRoute: typeof DashboardAssetsAddIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/users/edit/$id': {
      id: '/_dashboard/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof DashboardUsersEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/terms/edit/$id': {
      id: '/_dashboard/terms/edit/$id'
      path: '/terms/edit/$id'
      fullPath: '/terms/edit/$id'
      preLoaderRoute: typeof DashboardTermsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/lendings/edit/$id': {
      id: '/_dashboard/lendings/edit/$id'
      path: '/lendings/edit/$id'
      fullPath: '/lendings/edit/$id'
      preLoaderRoute: typeof DashboardLendingsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/groups-and-permissions/edit/$id': {
      id: '/_dashboard/groups-and-permissions/edit/$id'
      path: '/groups-and-permissions/edit/$id'
      fullPath: '/groups-and-permissions/edit/$id'
      preLoaderRoute: typeof DashboardGroupsAndPermissionsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/employees/edit/$id': {
      id: '/_dashboard/employees/edit/$id'
      path: '/employees/edit/$id'
      fullPath: '/employees/edit/$id'
      preLoaderRoute: typeof DashboardEmployeesEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/assets/edit/$id': {
      id: '/_dashboard/assets/edit/$id'
      path: '/assets/edit/$id'
      fullPath: '/assets/edit/$id'
      preLoaderRoute: typeof DashboardAssetsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/suppliers/edit/$id/': {
      id: '/_dashboard/suppliers/edit/$id/'
      path: '/suppliers/edit/$id'
      fullPath: '/suppliers/edit/$id'
      preLoaderRoute: typeof DashboardSuppliersEditIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAssetsIndexRoute: typeof DashboardAssetsIndexRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
  DashboardGroupsAndPermissionsIndexRoute: typeof DashboardGroupsAndPermissionsIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
  DashboardLendingsIndexRoute: typeof DashboardLendingsIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardSuppliersIndexRoute: typeof DashboardSuppliersIndexRoute
  DashboardTermsIndexRoute: typeof DashboardTermsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardAssetsEditIdRoute: typeof DashboardAssetsEditIdRoute
  DashboardEmployeesEditIdRoute: typeof DashboardEmployeesEditIdRoute
  DashboardGroupsAndPermissionsEditIdRoute: typeof DashboardGroupsAndPermissionsEditIdRoute
  DashboardLendingsEditIdRoute: typeof DashboardLendingsEditIdRoute
  DashboardTermsEditIdRoute: typeof DashboardTermsEditIdRoute
  DashboardUsersEditIdRoute: typeof DashboardUsersEditIdRoute
  DashboardAssetsAddIndexRoute: typeof DashboardAssetsAddIndexRoute
  DashboardAssetsImportIndexRoute: typeof DashboardAssetsImportIndexRoute
  DashboardEmployeesAddIndexRoute: typeof DashboardEmployeesAddIndexRoute
  DashboardGroupsAndPermissionsAddIndexRoute: typeof DashboardGroupsAndPermissionsAddIndexRoute
  DashboardInventoryViewIndexRoute: typeof DashboardInventoryViewIndexRoute
  DashboardInvoicesImportIndexRoute: typeof DashboardInvoicesImportIndexRoute
  DashboardLendingsAddIndexRoute: typeof DashboardLendingsAddIndexRoute
  DashboardSuppliersAddIndexRoute: typeof DashboardSuppliersAddIndexRoute
  DashboardTermsAddIndexRoute: typeof DashboardTermsAddIndexRoute
  DashboardUsersAddIndexRoute: typeof DashboardUsersAddIndexRoute
  DashboardSuppliersEditIdIndexRoute: typeof DashboardSuppliersEditIdIndexRoute
  DashboardAssetEvaluationsIndexRoute: typeof DashboardAssetEvaluationsIndexRoute
  DashboardAssetEvaluationsNewIndexRoute: typeof DashboardAssetEvaluationsNewIndexRoute
  DashboardAssetEvaluationsIdRoute: typeof DashboardAssetEvaluationsIdRoute
  DashboardPurchaseProcessesIndexRoute: typeof DashboardPurchaseProcessesIndexRoute
  DashboardPurchaseProcessesNewIndexRoute: typeof DashboardPurchaseProcessesNewIndexRoute
  DashboardPurchaseProcessesIdRoute: typeof DashboardPurchaseProcessesIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAssetsIndexRoute: DashboardAssetsIndexRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
  DashboardGroupsAndPermissionsIndexRoute:
    DashboardGroupsAndPermissionsIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
  DashboardLendingsIndexRoute: DashboardLendingsIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardSuppliersIndexRoute: DashboardSuppliersIndexRoute,
  DashboardTermsIndexRoute: DashboardTermsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardAssetsEditIdRoute: DashboardAssetsEditIdRoute,
  DashboardEmployeesEditIdRoute: DashboardEmployeesEditIdRoute,
  DashboardGroupsAndPermissionsEditIdRoute:
    DashboardGroupsAndPermissionsEditIdRoute,
  DashboardLendingsEditIdRoute: DashboardLendingsEditIdRoute,
  DashboardTermsEditIdRoute: DashboardTermsEditIdRoute,
  DashboardUsersEditIdRoute: DashboardUsersEditIdRoute,
  DashboardAssetsAddIndexRoute: DashboardAssetsAddIndexRoute,
  DashboardAssetsImportIndexRoute: DashboardAssetsImportIndexRoute,
  DashboardEmployeesAddIndexRoute: DashboardEmployeesAddIndexRoute,
  DashboardGroupsAndPermissionsAddIndexRoute:
    DashboardGroupsAndPermissionsAddIndexRoute,
  DashboardInventoryViewIndexRoute: DashboardInventoryViewIndexRoute,
  DashboardInvoicesImportIndexRoute: DashboardInvoicesImportIndexRoute,
  DashboardLendingsAddIndexRoute: DashboardLendingsAddIndexRoute,
  DashboardSuppliersAddIndexRoute: DashboardSuppliersAddIndexRoute,
  DashboardTermsAddIndexRoute: DashboardTermsAddIndexRoute,
  DashboardUsersAddIndexRoute: DashboardUsersAddIndexRoute,
  DashboardSuppliersEditIdIndexRoute: DashboardSuppliersEditIdIndexRoute,
  DashboardAssetEvaluationsIndexRoute: DashboardAssetEvaluationsIndexRoute,
  DashboardAssetEvaluationsNewIndexRoute: DashboardAssetEvaluationsNewIndexRoute,
  DashboardAssetEvaluationsIdRoute: DashboardAssetEvaluationsIdRoute,
  DashboardPurchaseProcessesIndexRoute: DashboardPurchaseProcessesIndexRoute,
  DashboardPurchaseProcessesNewIndexRoute:
    DashboardPurchaseProcessesNewIndexRoute,
  DashboardPurchaseProcessesIdRoute: DashboardPurchaseProcessesIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface InventoryInventoryFormRouteRouteChildren {
  InventoryInventoryFormIndexRoute: typeof InventoryInventoryFormIndexRoute
}

const InventoryInventoryFormRouteRouteChildren: InventoryInventoryFormRouteRouteChildren =
  {
    InventoryInventoryFormIndexRoute: InventoryInventoryFormIndexRoute,
  }

const InventoryInventoryFormRouteRouteWithChildren =
  InventoryInventoryFormRouteRoute._addFileChildren(
    InventoryInventoryFormRouteRouteChildren,
  )

interface InventoryRouteRouteChildren {
  InventoryInventoryFormRouteRoute: typeof InventoryInventoryFormRouteRouteWithChildren
  InventoryInventoryAccessIndexRoute: typeof InventoryInventoryAccessIndexRoute
}

const InventoryRouteRouteChildren: InventoryRouteRouteChildren = {
  InventoryInventoryFormRouteRoute:
    InventoryInventoryFormRouteRouteWithChildren,
  InventoryInventoryAccessIndexRoute: InventoryInventoryAccessIndexRoute,
}

const InventoryRouteRouteWithChildren = InventoryRouteRoute._addFileChildren(
  InventoryRouteRouteChildren,
)

interface AuthLoginRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthLoginRouteRouteChildren: AuthLoginRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthLoginRouteRouteWithChildren = AuthLoginRouteRoute._addFileChildren(
  AuthLoginRouteRouteChildren,
)

interface SuppliersApprovalRouteRouteChildren {
  SuppliersApprovalIndexRoute: typeof SuppliersApprovalIndexRoute
}

const SuppliersApprovalRouteRouteChildren: SuppliersApprovalRouteRouteChildren =
  {
    SuppliersApprovalIndexRoute: SuppliersApprovalIndexRoute,
  }

const SuppliersApprovalRouteRouteWithChildren =
  SuppliersApprovalRouteRoute._addFileChildren(
    SuppliersApprovalRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  InventoryRouteRoute: InventoryRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  AuthLoginRouteRoute: AuthLoginRouteRouteWithChildren,
  SuppliersApprovalRouteRoute: SuppliersApprovalRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
